#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.77.1.

use crate::api::*;
use core::panic::UnwindSafe;
use flutter_rust_bridge::*;
use std::ffi::c_void;
use std::sync::Arc;

// Section: imports

// Section: wire functions

fn wire_add_impl(
    port_: MessagePort,
    title: impl Wire2Api<String> + UnwindSafe,
    description: impl Wire2Api<String> + UnwindSafe,
    priority: impl Wire2Api<String> + UnwindSafe,
    day: impl Wire2Api<String> + UnwindSafe,
    time: impl Wire2Api<String> + UnwindSafe,
    status: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "add",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_title = title.wire2api();
            let api_description = description.wire2api();
            let api_priority = priority.wire2api();
            let api_day = day.wire2api();
            let api_time = time.wire2api();
            let api_status = status.wire2api();
            move |task_callback| {
                Ok(add(
                    api_title,
                    api_description,
                    api_priority,
                    api_day,
                    api_time,
                    api_status,
                ))
            }
        },
    )
}
fn wire_display_impl(port_: MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "display",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || move |task_callback| Ok(display()),
    )
}
fn wire_remove_todo_impl(port_: MessagePort, title: impl Wire2Api<String> + UnwindSafe) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "remove_todo",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_title = title.wire2api();
            move |task_callback| Ok(remove_todo(api_title))
        },
    )
}
fn wire_get_todos_impl(port_: MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "get_todos",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || move |task_callback| Ok(get_todos()),
    )
}
// Section: wrapper structs

// Section: static checks

// Section: allocate functions

// Section: related functions

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        (!self.is_null()).then(|| self.wire2api())
    }
}

impl Wire2Api<u8> for u8 {
    fn wire2api(self) -> u8 {
        self
    }
}

// Section: impl IntoDart

impl support::IntoDart for Todo {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.title.into_dart(),
            self.description.into_dart(),
            self.priority.into_dart(),
            self.day.into_dart(),
            self.time.into_dart(),
            self.status.into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for Todo {}

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

#[cfg(not(target_family = "wasm"))]
#[path = "bridge_generated.io.rs"]
mod io;
#[cfg(not(target_family = "wasm"))]
pub use io::*;
